apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-angular
  labels:
    app: front-angular
  
spec:
  selector:
    matchLabels:
      app: front-angular
    
     
  replicas: 1
  template:
    metadata:
      labels:
        app: front-angular
       
      
    spec:
      containers:
      - name: front-angular
        image: omarkorbi/front-angular
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: front-angular
  labels:
    app: front-angular
spec:
  type: NodePort
  selector:
    app: front-angular
  
  ports:
      
    - port: 80
      targetPort: 80
      nodePort: 30018
      protocol: TCP